org: jonasamorimpucminas
app: aws-node-express-dynamodb-api
service: aws-node-express-dynamodb-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [PollsTable, Arn]
  environment:
    POLLS_TABLE: polls_table_${sls:stage}
    VOTES_TABLE: votes_table_${sls:stage}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: user_table_${sls:stage}
    PollsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pollId
            AttributeType: S
        KeySchema:
          - AttributeName: pollId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: polls_table_${sls:stage}
    VotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: voteId
            AttributeType: S
        KeySchema:
          - AttributeName: voteId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: votes_table_${sls:stage}
